[package]
name = "random-geojson-points"
version = "0.1.0"
authors = ["Alex G Rice <alex@ricegeo.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geojson = "0.16"
rand = "0.7"